import SwiftUI

// ============================================================
//  SummaryView.swift — Daily report card screen
// ============================================================
//
//  WHERE IT FITS
//  -------------
//  Presented as a sheet from HomeView's bottom bar "Summary" button.
//  Displays the DaySummary generated by Gemini via SummaryViewModel.
//
//  SECTIONS (all optional — only shown when Gemini provides data)
//  --------
//  - DayHeaderCard: baby name + age + today's date
//  - OneLinerCard: warm one-sentence day summary (italic, tinted)
//  - StatsBarView: scrollable pill row (fed 6x, slept 3.5h, wet 4, etc.)
//  - FeedingSectionView: timeline entries + volume totals + flags
//  - SleepSectionView: nap/night entries + duration breakdown
//  - DiapersSectionView: counts + anomaly notes
//  - HealthSectionView: only shown when health events exist
//  - MilestonesSectionView: notable firsts
//  - MoodArcView: narrative paragraph about the day's mood
//  - PediatricianSummaryView: collapsible structured text for doctor visits
//  - ShareCardView: <280 char tweet with Share button
//  - LegacySummaryView: fallback for old backend response format

struct SummaryView: View {
    @EnvironmentObject var profile: BabyProfile
    @EnvironmentObject var eventStore: EventStore
    @EnvironmentObject var summaryVM: SummaryViewModel

    private var dateStr: String {
        let fmt = DateFormatter()
        fmt.dateFormat = "yyyy-MM-dd"
        return fmt.string(from: Date())
    }

    var body: some View {
        NavigationStack {
            Group {
                if summaryVM.isGenerating {
                    ProgressView("Generating summary…")
                        .frame(maxWidth: .infinity, maxHeight: .infinity)
                } else if let summary = summaryVM.summary {
                    SummaryContent(summary: summary, profile: profile)
                } else {
                    ContentUnavailableView(
                        "No summary yet",
                        systemImage: "doc.text",
                        description: Text("Tap Generate to create today's summary.")
                    )
                }
            }
            .navigationTitle("Today's Report")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Generate") {
                        Task {
                            await summaryVM.generateSummary(
                                babyName: profile.babyName,
                                ageMonths: profile.babyAgeMonths,
                                dateStr: dateStr
                            )
                        }
                    }
                    .disabled(summaryVM.isGenerating)
                }
            }
            .task {
                await summaryVM.fetchCachedSummary(dateStr: dateStr)
            }
        }
    }
}

// MARK: - Main content

struct SummaryContent: View {
    let summary: DaySummary
    let profile: BabyProfile

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                DayHeaderCard(profile: profile)
                if let oneLiner = summary.oneLiner ?? summary.narrative {
                    OneLinerCard(text: oneLiner)
                }
                if let stats = summary.statsBar {
                    StatsBarView(stats: stats)
                }
                if let feeding = summary.feeding {
                    FeedingSectionView(section: feeding)
                }
                if let sleep = summary.sleep {
                    SleepSectionView(section: sleep)
                }
                if let diapers = summary.diapers {
                    DiapersSectionView(section: diapers)
                }
                if let health = summary.health, !(health.entries ?? []).isEmpty {
                    HealthSectionView(section: health)
                }
                if let milestones = summary.milestones, !milestones.isEmpty {
                    MilestonesSectionView(milestones: milestones)
                }
                if let moodArc = summary.moodArc {
                    MoodArcView(text: moodArc)
                }
                if let ped = summary.pediatricianSummary {
                    PediatricianSummaryView(text: ped)
                }
                if let tweet = summary.socialTweet {
                    ShareCardView(tweet: tweet, babyName: profile.babyName)
                }
                // Legacy fallback for old backend responses
                if summary.oneLiner == nil, let legacy = summary.structured {
                    LegacySummaryView(structured: legacy)
                }
            }
            .padding(.vertical)
        }
    }
}

// MARK: - Day header

struct DayHeaderCard: View {
    let profile: BabyProfile

    var body: some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(formattedDate)
                .font(.headline)
                .foregroundColor(.secondary)
            HStack(spacing: 6) {
                Text(profile.babyName)
                    .font(.title2.bold())
                Text("·")
                    .foregroundColor(.secondary)
                Text(ageString)
                    .font(.title2)
                    .foregroundColor(.secondary)
            }
        }
        .padding(.horizontal)
    }

    private var formattedDate: String {
        let fmt = DateFormatter()
        fmt.dateFormat = "EEEE, MMMM d"
        return fmt.string(from: Date())
    }

    private var ageString: String {
        let months = profile.babyAgeMonths
        if months < 1 { return "newborn" }
        let years = months / 12
        let rem = months % 12
        if years == 0 { return "\(months) months" }
        if rem == 0 { return "\(years) year\(years == 1 ? "" : "s")" }
        return "\(years)y \(rem)mo"
    }
}

// MARK: - One-liner

struct OneLinerCard: View {
    let text: String

    var body: some View {
        Text(text)
            .font(.body)
            .italic()
            .foregroundColor(.primary)
            .padding()
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(Color.accentColor.opacity(0.08))
            .clipShape(RoundedRectangle(cornerRadius: 12))
            .padding(.horizontal)
    }
}

// MARK: - Stats bar

struct StatsBarView: View {
    let stats: DaySummary.StatsBar

    var body: some View {
        ScrollView(.horizontal, showsIndicators: false) {
            HStack(spacing: 10) {
                if let n = stats.feedCount {
                    StatPill(icon: "🍼", label: "Fed \(n)x")
                }
                if let h = stats.sleepHoursTotal {
                    StatPill(icon: "😴", label: "Slept \(String(format: "%.1f", h))h")
                }
                if let w = stats.wetCount {
                    StatPill(icon: "💧", label: "Wet \(w)")
                }
                if let d = stats.dirtyCount {
                    StatPill(icon: "💩", label: "Dirty \(d)")
                }
                if let status = stats.healthStatus {
                    StatPill(
                        icon: status == "flagged" ? "⚠️" : "🌡️",
                        label: status == "flagged" ? "Health flag" : "Normal",
                        highlighted: status == "flagged"
                    )
                }
            }
            .padding(.horizontal)
        }
    }
}

struct StatPill: View {
    let icon: String
    let label: String
    var highlighted: Bool = false

    var body: some View {
        HStack(spacing: 4) {
            Text(icon)
            Text(label).font(.caption.weight(.medium))
        }
        .padding(.horizontal, 12)
        .padding(.vertical, 6)
        .background(highlighted ? Color.orange.opacity(0.2) : Color(.secondarySystemBackground))
        .clipShape(Capsule())
    }
}

// MARK: - Feeding

struct FeedingSectionView: View {
    let section: DaySummary.FeedingSection

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            SectionHeader(
                emoji: "🍼",
                title: "Feeding",
                subtitle: subtitle
            )
            if let entries = section.entries, !entries.isEmpty {
                VStack(alignment: .leading, spacing: 4) {
                    ForEach(entries, id: \.time) { entry in
                        TimelineRow(time: entry.time, title: entry.type, detail: entry.detail)
                    }
                }
                .padding(.leading, 16)
            }
            if let flags = section.flags, !flags.isEmpty {
                ForEach(flags, id: \.self) { flag in
                    FlagRow(text: flag)
                }
            }
        }
        .padding(.horizontal)
    }

    private var subtitle: String {
        var parts: [String] = []
        if let n = section.totalCount { parts.append("\(n) feeds") }
        if let v = section.totalVolume { parts.append(v) }
        return parts.joined(separator: " · ")
    }
}

// MARK: - Sleep

struct SleepSectionView: View {
    let section: DaySummary.SleepSection

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            SectionHeader(emoji: "😴", title: "Sleep", subtitle: subtitle)
            if let entries = section.entries, !entries.isEmpty {
                VStack(alignment: .leading, spacing: 4) {
                    ForEach(entries, id: \.label) { entry in
                        TimelineRow(
                            time: entry.start,
                            title: "\(entry.label)\(endStr(entry))",
                            detail: durationAndNotes(entry)
                        )
                    }
                }
                .padding(.leading, 16)
            }
            if let flags = section.flags, !flags.isEmpty {
                ForEach(flags, id: \.self) { flag in FlagRow(text: flag) }
            }
        }
        .padding(.horizontal)
    }

    private func endStr(_ e: DaySummary.SleepEntry) -> String {
        guard let end = e.end else { return "" }
        return " – \(end)"
    }

    private func durationAndNotes(_ e: DaySummary.SleepEntry) -> String? {
        var parts: [String] = []
        if let mins = e.durationMinutes {
            let h = mins / 60; let m = mins % 60
            parts.append(h > 0 ? "\(h)h \(m)m" : "\(m)m")
        }
        if let n = e.notes { parts.append(n) }
        return parts.isEmpty ? nil : parts.joined(separator: " · ")
    }

    private var subtitle: String {
        guard let total = section.totalMinutes else { return "" }
        let h = total / 60; let m = total % 60
        var s = h > 0 ? "\(h)h \(m)m total" : "\(m)m total"
        if let day = section.dayMinutes, let night = section.nightMinutes {
            let dh = day / 60; let dm = day % 60
            let nh = night / 60; let nm = night % 60
            s += " · \(dh)h\(dm > 0 ? "\(dm)m" : "") day + \(nh)h\(nm > 0 ? "\(nm)m" : "") night"
        }
        return s
    }
}

// MARK: - Diapers

struct DiapersSectionView: View {
    let section: DaySummary.DiapersSection

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            SectionHeader(emoji: "🚼", title: "Diapers", subtitle: subtitle)
            if let note = section.note {
                Text(note)
                    .font(.body)
                    .foregroundColor(.secondary)
            }
        }
        .padding(.horizontal)
    }

    private var subtitle: String {
        var parts: [String] = []
        if let w = section.wetCount { parts.append("\(w) wet") }
        if let d = section.dirtyCount { parts.append("\(d) dirty") }
        return parts.joined(separator: " · ")
    }
}

// MARK: - Health

struct HealthSectionView: View {
    let section: DaySummary.HealthSection

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            SectionHeader(emoji: "🩺", title: "Health", subtitle: "")
            if let entries = section.entries {
                VStack(alignment: .leading, spacing: 4) {
                    ForEach(entries, id: \.time) { entry in
                        TimelineRow(time: entry.time, title: entry.detail, detail: nil)
                    }
                }
                .padding(.leading, 16)
            }
            if let summary = section.summary {
                Text(summary).font(.body).foregroundColor(.secondary)
            }
        }
        .padding(.horizontal)
    }
}

// MARK: - Milestones

struct MilestonesSectionView: View {
    let milestones: [String]

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            SectionHeader(emoji: "⭐", title: "Milestones & Moments", subtitle: "")
            VStack(alignment: .leading, spacing: 6) {
                ForEach(milestones, id: \.self) { item in
                    HStack(alignment: .top, spacing: 8) {
                        Text("•")
                        Text(item).font(.body)
                    }
                }
            }
        }
        .padding(.horizontal)
    }
}

// MARK: - Mood arc

struct MoodArcView: View {
    let text: String

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            SectionHeader(emoji: "🌈", title: "Mood & Behavior", subtitle: "")
            Text(text).font(.body).fixedSize(horizontal: false, vertical: true)
        }
        .padding(.horizontal)
    }
}

// MARK: - Pediatrician summary

struct PediatricianSummaryView: View {
    let text: String
    @State private var isExpanded = false

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            Button(action: { withAnimation { isExpanded.toggle() } }) {
                HStack {
                    SectionHeader(emoji: "👨‍⚕️", title: "For your next visit", subtitle: "")
                    Spacer()
                    Image(systemName: isExpanded ? "chevron.up" : "chevron.down")
                        .foregroundColor(.secondary)
                        .font(.caption)
                }
            }
            .buttonStyle(.plain)
            if isExpanded {
                Text(text)
                    .font(.body.monospaced())
                    .foregroundColor(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
                    .padding()
                    .background(Color(.secondarySystemBackground))
                    .clipShape(RoundedRectangle(cornerRadius: 10))
            }
        }
        .padding(.horizontal)
    }
}

// MARK: - Share card

struct ShareCardView: View {
    let tweet: String
    let babyName: String

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            SectionHeader(emoji: "✨", title: "Share", subtitle: "")
            Text(tweet)
                .font(.body)
                .padding()
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(Color(.secondarySystemBackground))
                .clipShape(RoundedRectangle(cornerRadius: 12))
            ShareLink(item: tweet) {
                Label("Share", systemImage: "square.and.arrow.up")
            }
            .buttonStyle(.bordered)
        }
        .padding(.horizontal)
    }
}

// MARK: - Shared sub-views

struct SectionHeader: View {
    let emoji: String
    let title: String
    let subtitle: String

    var body: some View {
        HStack(alignment: .firstTextBaseline, spacing: 4) {
            Text("\(emoji) \(title)").font(.headline)
            if !subtitle.isEmpty {
                Text("· \(subtitle)")
                    .font(.subheadline)
                    .foregroundColor(.secondary)
            }
        }
    }
}

struct TimelineRow: View {
    let time: String
    let title: String
    let detail: String?

    var body: some View {
        HStack(alignment: .top, spacing: 12) {
            Text(time)
                .font(.caption.monospacedDigit())
                .foregroundColor(.secondary)
                .frame(width: 62, alignment: .trailing)
            VStack(alignment: .leading, spacing: 1) {
                Text(title).font(.subheadline)
                if let d = detail {
                    Text(d).font(.caption).foregroundColor(.secondary)
                }
            }
        }
    }
}

struct FlagRow: View {
    let text: String

    var body: some View {
        HStack(spacing: 6) {
            Image(systemName: "exclamationmark.triangle.fill")
                .foregroundColor(.orange)
                .font(.caption)
            Text(text).font(.caption).foregroundColor(.orange)
        }
    }
}

// MARK: - Legacy fallback (old backend responses)

struct LegacySummaryView: View {
    let structured: DaySummary.Structured

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            if let glance = structured.glance, !glance.isEmpty {
                ScrollView(.horizontal, showsIndicators: false) {
                    HStack {
                        ForEach(glance, id: \.self) { item in
                            Text(item)
                                .font(.caption)
                                .padding(.horizontal, 10)
                                .padding(.vertical, 5)
                                .background(Color.accentColor.opacity(0.15))
                                .clipShape(Capsule())
                        }
                    }
                    .padding(.horizontal)
                }
            }
            if let eating = structured.eating {
                VStack(alignment: .leading, spacing: 4) {
                    Text("🍼 Feeding").font(.headline)
                    if let s = eating.summary { Text(s).font(.body) }
                }
                .padding(.horizontal)
            }
            if let nap = structured.nap {
                VStack(alignment: .leading, spacing: 4) {
                    Text("😴 Sleep").font(.headline)
                    if let s = nap.summary { Text(s).font(.body) }
                }
                .padding(.horizontal)
            }
            if let milestone = structured.milestone, let items = milestone.items, !items.isEmpty {
                VStack(alignment: .leading, spacing: 4) {
                    Text("⭐ Milestones").font(.headline)
                    ForEach(items, id: \.self) { Text("• \($0)").font(.body) }
                }
                .padding(.horizontal)
            }
        }
    }
}
